### ISSUE TITLE
grad() got an unexpected keyword argument 'mode'

### ISSUE THREAD

**Issue by ehannigan** [google/tangent#51]
I tried running the interactive notebook provided, but I continue to get the error 

grad() got an unexpected keyword argument 'mode'

I tested this in both python 2.7 and python 3.6 and got the same problem.

**Comment by alexbw** [comment]
Hey, the API changed a bit, s.t. grad() implies a true gradient, and also
only uses reverse mode, so we got rid of the 'mode' keyword. Unfortunately,
we didn't change the demo notebook. I'll update that ASAP.

Best,
Alex

**Comment by alexbw** [comment]
Resolved in a new colab notebook on the README.

**Comment by jpeg729** [comment]
The README.md still showcases the old code and the old result.
